version: '3.8'

services:
  app:
    container_name: air-apis
    image: air-apis
    build:
      context: .
      target: development
    volumes:
      - .:/app
    depends_on:
      - database  
    ports:
      - 8080:8080
    networks:
      - go-ci-cd-net
  database:
    image: postgres
    restart: always
    hostname: db 
    networks:
      - go-ci-cd-net 
    env_file:
      - .env 
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
               
networks:
  go-ci-cd-net:
    driver: bridge
