name: Deploy to Amazon ECS
on:

  push:

    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
  
# # Step 3
   
   - name: Create CodeDeploy Deployment
     id: deploy
     run: |
      aws deploy create-deployment \
      -application-name air-api-ec2 \
      -deployment-group-name Air-Api-devops-deploy \
      -deployment-config-name CodeDeployDefault.OneAtATime \
      -github-location repository=${{ github.repository }},commitId=${{ github.sha }}